---
title: "Qualitative Interactions: Data Analysis"
author: "Aaron Hudson"
date: "Nov 26, 2023"
output: pdf_document
header-includes:
- \usepackage{graphicx}
- \usepackage{dsfont}
- \usepackage{lipsum}
- \usepackage{setspace}\doublespacing
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      cache = TRUE, results = 'hide')
```

```{r Packages}
library(Biobase)
library(RTCGA)
library(RTCGA.clinical) # survival times
library(RTCGA.rnaseq) # genes' expression
library(genefu)
library(graphite)
library(igraph)
library(org.Hs.eg.db)
library(xtable)

source('QualInt.R')
```

```{r PreProcess}
###################################################
### 1. Pre-processing
###################################################

# access expression data, survival data, and ER status
clinical.data <- as.data.frame(cbind(survivalTCGA(BRCA.clinical), BRCA.clinical[,23]))
expression.data.full <- expressionsTCGA(BRCA.rnaseq)
expression.data <- as.data.frame(expression.data.full)[,-20533]

# log transform 
for(i in 2:ncol(expression.data)) {
  expression.data[,i] <- log1p(as.numeric(expression.data[,i]))
}

# sort through all patient data to look for duplicates
# in the presence of duplicates, take the patient with highest full barcode (in lex. order)
expression.data$short_barcode <- substr(expression.data$bcr_patient_barcode, 1, 12)
for(i in 1:nrow(expression.data)) {
  id <- expression.data$short_barcode[i]
  matches <- which(expression.data$short_barcode == id)
  if(length(matches) > 1) {
    full.ids <- expression.data$bcr_patient_barcode[matches]
    highest.lex <- order(full.ids, decreasing = TRUE)[1]
    expression.data <- expression.data[-matches[-highest.lex],]
  }
}

expression.data$bcr_patient_barcode <- substr(expression.data$bcr_patient_barcode, 1, 12)

# make sure both clinical and expression data are recorded on same samples
clinical.data <- clinical.data[clinical.data$bcr_patient_barcode %in%
                               expression.data$bcr_patient_barcode,]
expression.data <- expression.data[expression.data$bcr_patient_barcode %in%
                                   clinical.data$bcr_patient_barcode,]
all(expression.data$bcr_patient_barcode == clinical.data$bcr_patient_barcode)

# rename columns
expression.data <- expression.data[,-1]
colnames(expression.data) <- gsub( "\\|.*$", "", colnames(expression.data))

# remove observations with missing ER
colnames(clinical.data)[4] <- "ER"
missing.ER <- with(clinical.data, is.na(ER) | (ER == "indeterminate"))
expression.data <- expression.data[!missing.ER, ]
clinical.data <- clinical.data[!missing.ER,]
```

```{r Network1}
###########################################
### 2A. Network Analysis: Methods
###########################################

# get KEGG genes
keggpaths <- as.list(pathways("hsapiens", "kegg"))
indx <- which(names(keggpaths) %in% "Breast cancer")
BCpath <- keggpaths[[indx]]
BCpath <- convertIdentifiers(BCpath, "symbol")
BCgenes <- nodes(BCpath)
BCgenes <- substr(BCgenes, 8, 30)
KEGGgenes <- BCgenes[BCgenes %in% colnames(expression.data)]

KEGG.expression <- expression.data[,KEGGgenes]
ER.Plus <- KEGG.expression[clinical.data$ER == "positive",]
ER.Neg <- KEGG.expression[clinical.data$ER == "negative",]

p <- ncol(ER.Plus)

n.plus <- nrow(ER.Plus)
n.neg <- nrow(ER.Neg)
n <- c(n.plus, n.neg)

Est.Plus <- cor(ER.Plus)
SE.Plus <- sqrt((1 - Est.Plus^2)/(n.plus - 2))

Est.Neg <- cor(ER.Neg)
SE.Neg <- (1 - Est.Neg^2)/sqrt(n.neg - 2)

p.vals <- matrix(NA, p, p)
kappas <- c(1.5, 2, 2.5, 3)
p.vals <- array(NA, dim = c(p, p, length(kappas)))
kmax <- matrix(NA, p, p)
alpha <- .05
for(i in 1:(p-1)) {
  for(j in (i+1):p) {
    for(k in 1:length(kappas)) {
      theta.hat <- c(Est.Plus[i,j], Est.Neg[i,j])
      standard.error <- c(SE.Plus[i,j], SE.Neg[i,j])
      p.vals[i,j,k] <- RelDifLRT(theta.hat, standard.error, n, kappa = kappas[k])$p.val
      p.vals[j,i,k] <- p.vals[i,j,k]
    }
  }
  kmax[i,j] <- kappa.max(theta.hat, standard.error, n, alpha)
  kmax[j,i] <- kmax[i,j]
}
```

```{r Network2}
####################################
### 2B: Network Analysis: Plots
### Primary -- kappa = 2
####################################
set.seed(206)

significant.kappa2 <- which(p.vals[,,2] < .05/choose(p, 2), arr.ind = T)
adj <- apply(p.vals[,,2], c(1,2), function(x) ifelse(x < .05/choose(p, 2), 1, 0))
adj.plus <- adj * apply(abs(Est.Plus)/abs(Est.Neg), c(1,2),
                        function(x) ifelse(x > 1, 1, 0))
adj.neg <- adj * apply(abs(Est.Neg)/abs(Est.Plus), c(1,2),
                       function(x) ifelse(x > 1, 1, 0))

diag(adj) <- 0

rownames(adj) <- colnames(ER.Plus)
colnames(adj) <- colnames(ER.Plus)

adj.red <- adj[which(rowSums(adj) > 0), which(rowSums(adj) > 0)]


net <- graph_from_adjacency_matrix(adj.red, mode = "undirected")
net.plus <- graph_from_adjacency_matrix(adj.plus, mode = "undirected")
net.neg <- graph_from_adjacency_matrix(adj.neg, mode = "undirected")
l <- layout.circle(net)

edges.net <- apply(as_edgelist(net), 1, paste, collapse = "--")
edges.plus <- apply(as_edgelist(net.plus), 1, paste, collapse = "--")
edges.neg <- apply(as_edgelist(net.neg), 1, paste, collapse = "--")


E(net)$color <- ifelse(edges.net %in% edges.plus, "red", "blue")
V(net)$color <- "white"
V(net)$size <- 20

plot(net, vertex.shape="circle",
     cex = 1, edge.width = 3, layout = layout.fruchterman.reingold(net),
     vertex.label.color="black", vertex.frame.color = "white", 
     vertex.label.cex = .7, xlim  = c(.1, .5))
```

```{r Network3, results='asis'}
####################################
### 2C: Network Analysis: Table
### Secondary -- p-values
####################################
p.vals.temp <- p.vals
p.vals.temp[cbind(t(combn(1:145, 2)), 2)] <- 1
significant<- which(p.vals.temp[,,2] < .05/choose(p, 2), arr.ind = T)
significant <- significant[order(significant[,1]),]

tab.network <- cbind(p.vals[cbind(significant,1)],
                     p.vals[cbind(significant,2)],
                     p.vals[cbind(significant,3)],
                     p.vals[cbind(significant,4)]) * choose(p, 2)
tab.network <- apply(tab.network, c(1,2), function(x) min(c(x,1)))
tab.network <- signif(tab.network, 2)

tab.rownames <- paste0("(", colnames(ER.Plus)[significant[,1]], 
                       ", ", colnames(ER.Neg)[significant[,2]], ")")
tab.network <- cbind(tab.rownames, tab.network)
tab.network <- rbind(c("Gene Pair","$\\kappa = 1.5$", "$\\kappa = 2$", "$\\kappa = 2.5$", "$\\kappa = 3$"),
                     tab.network)

print(xtable(tab.network[,-2]),
      include.rowname = FALSE,
      include.colname = FALSE,
      sanitize.text.function = function(x) {x})
```


```{r, results = 'asis'}
# Number of deaths in each group:
# with(PAM50.full, sum(ER == "positive" & patient.vital_status == 1))
# with(PAM50.full, sum(ER == "negative" & patient.vital_status == 1))
```

```{r Biomarker1}
####################################
### 3A. Biomarker Analysis: Methods
####################################
KEGG.full <- cbind(KEGG.expression, clinical.data)

plus.models <- lapply(KEGGgenes,
                      function(x) 
                      coxph(Surv(time = times, event = patient.vital_status) ~ 
                            subset(KEGG.full, ER == "positive")[,x],
                            data = subset(KEGG.full, ER == "positive"))
                      )
neg.models <- lapply(KEGGgenes,
                     function(x) 
                     coxph(Surv(time = times, event = patient.vital_status) ~ 
                           subset(KEGG.full, ER == "negative")[,x],
                           data = subset(KEGG.full, ER == "negative"))
                      )

plus.hrs <- sapply(plus.models, function(x) summary(x)$coefficients[1])
plus.ses <- sapply(plus.models, function(x) summary(x)$coefficients[3])
neg.hrs <- sapply(neg.models, function(x) summary(x)$coefficients[1])
neg.ses <- sapply(neg.models, function(x) summary(x)$coefficients[3])

alphas <- c(.1, .05, .025, .01)
p <- length(KEGGgenes)
# kappa.surv <- numeric(p)
kappa.surv <- matrix(NA, nrow = p, ncol = length(alphas))
for(k in 1:length(alphas)) { 
  for(j in 1:p) {
    theta.hat <- c(plus.hrs[j], neg.hrs[j])
    standard.error <- c(plus.ses[j], neg.ses[j])
    n <- c(n.plus, n.neg)
    kappa.surv[j,k] <- kappa.max(theta.hat,
                                standard.error,
                                n,
                                alpha = alphas[k])
  }
}


```

```{r Biomarker2}
####################################
### 3B. Biomarker Analysis: Plots
####################################
qual.ints <- which(kappa.surv[,1] > 1)
plus.dots <- which(kappa.surv[,1] > 1 & (abs(plus.hrs) > abs(neg.hrs)))
neg.dots <- which(kappa.surv[,1] > 1 & (abs(plus.hrs) < abs(neg.hrs)))

par(pty = "s")
plot(plus.hrs, neg.hrs, xlim = c(-2.5, 2.5),
     ylim = c(-2.5, 2.5), pch = 16,
     xlab = "ER+", ylab = "ER-", col = "grey70")
abline(v = 0, h = 0, lty = 2)
points(plus.hrs[plus.dots], neg.hrs[plus.dots],
       col = "blue", cex = 1.625, pch = 18)
points(plus.hrs[neg.dots], neg.hrs[neg.dots],
       col = "red", cex = 1.5, pch = 17)


abline(a = 0, b = 1, lty = 2, col = "grey")
```

```{r Biomarker3, results='asis'}
####################################
### 3C. Biomarker Analysis: Tables
####################################
library(xtable)
tab <- data.frame(genes = KEGGgenes,
                  plus.hrs = paste0(round(plus.hrs, 2), " (",
                                    round(plus.ses, 2), ")"), 
                  neg.hrs = paste0(round(neg.hrs, 2), " (",
                                   round(neg.ses, 2), ")"),
                  kappa = kappa.surv)
tab <- tab[base::order(kappa.surv[,1], decreasing = TRUE),]
# colnames(tab) <- c("Gene", 
#                    "ER+ Log HR (SE)", "ER- Log HR (SE)",
#                    "$\\kappa^{\\alpha}_{\\max}$")

addtorow <- list()
addtorow$pos <- list(-1, 0)
addtorow$command <- c(paste0(paste0('Gene & ER+ Log HR (SE) & ER- Log HR (SE) & \\multicolumn{4}{c}{', "$\\kappa^{\\alpha}_{\\max}$", '}'), '\\\\'),
                      "& & & $\\alpha = .1$ & $\\alpha = .05$ & $\\alpha = .025$ & $\\alpha = .01$ \\\\")

rownames(tab) <- NULL
tab <- tab[sort(kappa.surv[,1],decreasing = TRUE) > 1, ]
print(xtable(tab),
      include.rowname = FALSE,
      include.colname = FALSE,
      sanitize.text.function = function(x) {x},
      add.to.row = addtorow)
```
